### ISSUE TITLE
Does this lib support po or xliff format?

### ISSUE THREAD

**Issue by jnak** [transifex/openformats#31]
Does this lib support po or xliff format?
You guys seem to suggest so in the Readme but I can't find any reference in the code.

Thanks

**Comment by luzpaz** [comment]
bump

**Comment by jnak** [comment]
Someone from support contacted me and confirmed that they do. Sadly to use the xliff format, you have to pay the $300 monthly plan, which we do but feels totally unjustified since it is supposed to be the new internationalization format standard...
